# Generated by Django 5.2.3 on 2025-07-01 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
                'db_table': 'PerfilUsuario',
            },
        ),
        migrations.CreateModel(
            name='FavoritosCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCampeonato', models.IntegerField()),
                ('Nome', models.CharField(max_length=255)),
                ('Pais', models.CharField(blank=True, max_length=100, null=True)),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competição Favorita',
                'verbose_name_plural': 'Competições Favoritas',
                'db_table': 'FavoritosCompeticao',
                'unique_together': {('IdUsuario', 'IdCampeonato')},
            },
        ),
        migrations.CreateModel(
            name='FavoritosJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdJogador', models.IntegerField()),
                ('Nome', models.CharField(max_length=255)),
                ('Nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('Posicao', models.CharField(blank=True, max_length=100, null=True)),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador Favorito',
                'verbose_name_plural': 'Jogadores Favoritos',
                'db_table': 'FavoritosJogador',
                'unique_together': {('IdUsuario', 'IdJogador')},
            },
        ),
        migrations.CreateModel(
            name='FavoritosTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTime', models.IntegerField()),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Favorito',
                'verbose_name_plural': 'Times Favoritos',
                'db_table': 'FavoritosTime',
                'unique_together': {('IdUsuario', 'IdTime')},
            },
        ),
    ]
